"""
generation/consumer_view.py — strips the typed-claim/citation internals
from a generated answer for the DEFAULT consumer-facing view: technical
evidence should be invisible by default but not deleted — the full
tagged/cited text stays available
(api/main.py returns it as `answer_technical`) for an optional
"why this answer?" view, and SourcesPanel.jsx already renders the actual
citations separately.

Purely structural (regex stripping), NOT an LLM rewrite — no extra
provider quota spent, no new hallucination surface. This is safe to do
because the underlying sentence content generated by SYSTEM_PROMPT is
already natural English; the technical noise is almost entirely the
leading `[TAG]` marker and the trailing `(source_file.md, heading)`
citation, both removed here. Same regex-stripping style already used in
api/main.py's `_build_sources()` for snippet cleanup (`_MD_HEADING_RE`/
`_MD_BOLD_RE`) — reused conventions, not a new pattern.
"""
import re

from generation.groundedness import CITATION_GROUP_RE, CITATION_PART_RE, TAG_RE, UNVERIFIED_MARKER
from generation.consistency import CONTRADICTION_MARKER_RE

# Reuses groundedness.py's TAG_RE (matches any bracketed all-caps tag
# shape, not just an exact known tag) so a model typo like "[INTERPRETION]"
# still gets stripped here instead of leaking to the consumer-facing
# answer — see TAG_RE's docstring for the real case this fixes.
_TAG_RE = re.compile(TAG_RE.pattern + r"\s*")
_WHITESPACE_RE = re.compile(r"[ \t]+")
_BLANK_LINES_RE = re.compile(r"\n{3,}")

# Catches a malformed citation the model sometimes writes as bare
# "(products.sqlite)" / "(all from products.sqlite)" / a bare KB filename
# like "(ingredient_knowledge_base.md)" instead of the required
# "(source_file.ext, ref)" shape — CITATION_PART_RE (correctly) requires a
# comma-separated "file, ref" pair and won't match any of these incomplete
# forms, so _strip_citation_group's stricter check leaves them alone.
# "products.sqlite" and this project's own KB filenames are fixed literals
# used only for this project's own citations, never a legitimate
# parenthetical aside, so stripping any parenthetical that MENTIONS one of
# them — anywhere inside the parens, not just as a strict prefix — carries
# none of the false-positive risk _strip_citation_group's generic check
# guards against for arbitrary "(...)" asides.
#
# Confirmed real, live (2026-08-28), two distinct leaks in the same
# deployed answer: "...total sugars: 1.9 g (all from products.sqlite)."
# (the original strict-prefix-only version of this regex required the
# parens to START with "products.sqlite", so wording like "all from ..."
# in front of it defeated the match entirely) and "...and DATEM (GMP for
# bread) (ingredient_knowledge_base.md)." (a bare filename with no ref at
# all — a shape this regex never covered before this fix, only the
# products.sqlite case).
_INTERNAL_FILENAME_CITATION_RE = re.compile(
    r"\([^()]*\b(?:products\.sqlite|[\w\-]+\.(?:md|json|txt|csv))\b[^()]*\)", re.IGNORECASE,
)

# Catches the model occasionally citing with the internal prompt's own
# "Source N: file.md, Chunk X" labeling (build_context_block() prefixes
# each retrieved chunk with "[Source N: ...]" so the model can tell them
# apart) instead of the required bare "(file.md, Chunk X)" shape —
# SYSTEM_PROMPT explicitly tells it not to do this, but compliance isn't
# 100%. Confirmed real 2026-08-21: "(Source 4, Chunk 40)" leaked straight
# into a consumer answer since CITATION_PART_RE (correctly) requires
# group 1 to look like a real "file.ext", which "Source 4" never does, so
# _strip_citation_group's stricter check left it alone. "Source N" is only
# ever this project's own internal chunk label, never a legitimate
# parenthetical aside, so stripping it outright is safe the same way the
# products.sqlite fallback above is.
_SOURCE_LABEL_CITATION_RE = re.compile(r"\(\s*Source\s+\d+\s*(?:[:,]\s*[^()]*)?\)", re.IGNORECASE)


def _strip_citation_group(match: re.Match) -> str:
    """
    CITATION_GROUP_RE matches ANY "(...)" — most of them really are
    citations here, but a legitimate parenthetical aside like "(INS 150c)"
    matches the same bracket shape and must NOT be stripped. Only remove
    a group whose content actually parses as a real "(file.ext, ref)"
    citation (checked with CITATION_PART_RE, reused from groundedness.py
    rather than re-deriving the citation shape) — everything else is left
    exactly as the model wrote it.
    """
    inner = match.group(1)
    if any(CITATION_PART_RE.match(part.strip()) for part in inner.split(";")):
        return ""
    return match.group(0)


def to_consumer_friendly(answer: str) -> str:
    text = _TAG_RE.sub("", answer)
    text = _INTERNAL_FILENAME_CITATION_RE.sub("", text)
    text = _SOURCE_LABEL_CITATION_RE.sub("", text)
    text = CITATION_GROUP_RE.sub(_strip_citation_group, text)
    text = text.replace(UNVERIFIED_MARKER.strip(), "")
    text = CONTRADICTION_MARKER_RE.sub("", text)
    # Citation removal can leave a stray space before sentence punctuation
    # (e.g. "43g of sugar . Next sentence") — tidy it up.
    text = re.sub(r"\s+([.,;])", r"\1", text)
    # A citation sitting between two periods (source text already ends in
    # "." right before the citation, and the citation's own sentence ends
    # in "." too) leaves "). ." once the citation is stripped, which the
    # rule above collapses into ".." — confirmed real 2026-08-21 on
    # ingredients_raw answers ("...Gram Meal (0.4%).."). Collapse any
    # run of periods left behind into one.
    text = re.sub(r"\.{2,}", ".", text)
    text = _WHITESPACE_RE.sub(" ", text)
    text = _BLANK_LINES_RE.sub("\n\n", text)
    return text.strip()
